# Generated by Django 3.2 on 2021-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_appointment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approval',
            field=models.IntegerField(choices=[(-1, 'Waiting doctors approval'), (0, 'Denied'), (1, 'Approved')], default=-1),
        ),
    ]
