# Generated by Django 3.2 on 2021-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_appointment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='disease_details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
