# Generated by Django 3.2 on 2021-04-17 17:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_hospital.user_set+', to='contenttypes.contenttype')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Hospital.user')),
                ('fees', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qualifications', models.TextField()),
                ('availability', models.BooleanField(default=False)),
                ('desc', models.TextField()),
                ('specilization', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Hospital.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Hospital.user')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_info', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Hospital.user',),
        ),
    ]
