# Generated by Django 3.2 on 2021-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
