# Generated by Django 3.2 on 2021-04-18 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20210418_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
